using System.Text;

namespace HLX.GamelibGenerator;

/// <summary>
/// Emits the Haxe wrapper source; every generated member resolves by name at
/// runtime through <c>hlx.runtime.HlxRuntime</c>.
/// </summary>
internal static class HxEmitter
{
    private const string Header =
        "// AUTO-GENERATED by HLX.GamelibGenerator - do not edit by hand.\n" +
        "// Regenerate from the game's own hlboot.dat instead of hand-patching this file.\n";

    public static string EmitClass(GameClass c)
    {
        var sb = new StringBuilder();
        sb.Append(Header);
        EmitPackage(sb, c.Package);
        var needsResolvedMember = c.Methods.Count > 0
            || c.Fields.Any(f => f.HasRealGetter || f.HasRealSetter)
            || c.StaticFields.Any(f => f.HasRealGetter || f.HasRealSetter);
        EmitImports(sb, needsResolvedMember: needsResolvedMember);
        EmitNotes(sb, c.Notes);

        var runtimeName = c.RuntimeTypeName ?? c.FullName;
        EmitClassHeader(sb, c);
        EmitFields(sb, runtimeName, c.Fields, indent: "    ");
        EmitStaticFields(sb, runtimeName, c.StaticFields, indent: "    ");
        EmitMethods(sb, runtimeName, c.Methods, indent: "    ");
        EmitConstructorFactory(sb, runtimeName, c.ShortName, c.Constructor, indent: "    ");
        sb.Append("}\n");
        return sb.ToString();
    }

    // With a generated ancestor, chain onto its abstract via @:forward instead of
    // Dynamic - gives free member access and implicit upcasting, and composes
    // across multiple chained levels on its own.
    private static void EmitClassHeader(StringBuilder sb, GameClass c)
    {
        if (c.ParentFullName == null)
        {
            sb.Append($"abstract {c.ShortName}(Dynamic) {{\n");
            return;
        }
        sb.Append("@:forward\n");
        sb.Append($"abstract {c.ShortName}({c.ParentFullName}) from {c.ParentFullName} to {c.ParentFullName} {{\n");
    }

    // Unlike every other accessor here, a constructor has no by-name reflective
    // slot to resolve at runtime - the findex baked in below was recovered offline
    // by ConstructorCollector's bytecode scan, and is more fragile across game
    // recompiles than a name-resolved member.
    private static void EmitConstructorFactory(StringBuilder sb, string ownerFullName, string shortName, GameConstructor? ctor, string indent)
    {
        if (ctor == null) return;
        var paramList = string.Join(", ", ctor.Params.Select((p, i) => $"a{i}:{p.HaxeType}"));
        var argsArray = string.Join(", ", Enumerable.Range(0, ctor.Params.Count).Select(i => $"a{i}"));

        var notes = ctor.Params.Select((p, i) => (Label: $"arg{i}", p.FallbackReason))
            .Where(x => x.FallbackReason != null)
            .Select(x => $"{x.Label}: {x.FallbackReason}")
            .ToList();
        if (notes.Count > 0)
            sb.Append($"{indent}// {string.Join("; ", notes)}\n");

        sb.Append($"{indent}// findex {ctor.Findex}: bytecode-recovered constructor, more version-fragile than\n");
        sb.Append($"{indent}// this class's other members - regenerate this gamelib after any game update.\n");
        sb.Append($"{indent}public inline function new({paramList}) {{\n");
        sb.Append($"{indent}    var t = HlxRuntime.resolveType(\"{ownerFullName}\");\n");
        sb.Append($"{indent}    this = HlxRuntime.constructInstance(t, {ctor.Findex}, [{argsArray}]);\n");
        sb.Append($"{indent}}}\n\n");
    }

    // Reflection-accessor wrapper, not a real Haxe `enum`: casting a Dynamic value to
    // an independently-declared, structurally-identical `enum` throws at runtime on
    // the hl target, so switch-based pattern matching against a generated wrapper is
    // unsafe. Type.enumIndex/enumConstructor/enumParameters work regardless of the
    // value's nominal type, so those are used instead.
    public static string EmitEnum(GameEnum e)
    {
        var sb = new StringBuilder();
        sb.Append(Header);
        EmitPackage(sb, e.Package);
        // Only param-taking constructors below need ResolvedMember (0-arg ones read a
        // plain static field, no caching involved - see the branch below for why).
        var needsResolvedMember = e.Constructors.Any(c => c.ParamTypes.Count > 0);
        EmitImports(sb, needsResolvedMember: needsResolvedMember);
        EmitNotes(sb, e.Notes);
        sb.Append(
            $"// Reflection-based wrapper for the real HL enum '{e.FullName}' - not a real\n" +
            "// Haxe `enum` (switch-casting a generated enum wrapper is unsafe on hl).\n" +
            "// Constructors (index: name(paramTypes)):\n");
        foreach (var c in e.Constructors)
        {
            var ps = string.Join(", ", c.ParamTypes.Select(p => p.HaxeType));
            sb.Append($"//   {c.Index}: {c.Name}({ps})\n");
        }

        var runtimeName = e.RuntimeTypeName ?? e.FullName;
        sb.Append($"abstract {e.ShortName}(Dynamic) {{\n");
        // "std.Type", not bare "Type": avoids resolving to a same-package generated
        // type also named Type (e.g. hxsl.Type) instead of the real stdlib one.
        sb.Append(
            "    public inline function getIndex():Int\n" +
            "        return std.Type.enumIndex(cast this);\n\n" +
            "    public inline function getConstructorName():String\n" +
            "        return std.Type.enumConstructor(cast this);\n\n" +
            "    public inline function getParams():Array<Dynamic>\n" +
            "        return std.Type.enumParameters(cast this);\n\n");

        var used = new HashSet<string>(StringComparer.Ordinal) { "getIndex", "getConstructorName", "getParams" };
        foreach (var c in e.Constructors)
        {
            var isName = "is" + c.Name;
            if (Naming.IsValidPlainIdentifier(isName) && used.Add(isName))
                sb.Append($"    public inline function {isName}():Bool\n        return getIndex() == {c.Index};\n\n");

            if (!Naming.IsValidPlainIdentifier(c.Name) || !used.Add(c.Name)) continue;

            if (c.ParamTypes.Count == 0)
            {
                sb.Append($"    public static var {c.Name}(get, never):{e.ShortName};\n");
                sb.Append($"    static inline function get_{c.Name}():{e.ShortName}\n");
                sb.Append($"        return HlxRuntime.resolveStaticField(HlxRuntime.resolveType(\"{runtimeName}\"), \"{c.Name}\");\n\n");
            }
            else
            {
                // Mirrors EmitMethods' own IsStatic=true branch exactly.
                var paramList = string.Join(", ", c.ParamTypes.Select((p, i) => $"a{i}:{p.HaxeType}"));
                var argsForCall = string.Join(", ", Enumerable.Range(0, c.ParamTypes.Count).Select(i => $"a{i}"));
                var cacheVar = "__hlxEnumCtor_" + c.Name;

                var notes = c.ParamTypes.Select((p, i) => (Label: $"arg{i}", p.FallbackReason))
                    .Where(x => x.FallbackReason != null)
                    .Select(x => $"{x.Label}: {x.FallbackReason}")
                    .ToList();
                if (notes.Count > 0)
                    sb.Append($"    // {string.Join("; ", notes)}\n");

                sb.Append($"    static var {cacheVar}:ResolvedMember;\n");
                sb.Append($"    public static function {c.Name}({paramList}):{e.ShortName} {{\n");
                sb.Append($"        if ({cacheVar} == null)\n");
                sb.Append($"            {cacheVar} = HlxRuntime.resolveStaticMember(HlxRuntime.resolveType(\"{runtimeName}\"), \"{c.Name}\");\n");
                sb.Append($"        return HlxRuntime.callResolved({cacheVar}, [{argsForCall}]);\n");
                sb.Append("    }\n\n");
            }
        }

        sb.Append("}\n");
        return sb.ToString();
    }

    public static string EmitGenericGroup(GenericGroup g)
    {
        var sb = new StringBuilder();
        sb.Append(Header);
        sb.Append(
            "// Collapsed @:generic monomorphization group (fields only).\n" +
            $"// Instantiations collapsed: {string.Join(", ", g.Instantiations)}\n");
        EmitPackage(sb, g.Package);
        EmitImports(sb, needsResolvedMember: g.Fields.Any(f => f.HasRealGetter || f.HasRealSetter));

        sb.Append($"abstract {g.ShortName}<T>(Dynamic) {{\n");
        EmitFields(sb, g.FullName, g.Fields, indent: "    ");
        sb.Append("}\n");
        return sb.ToString();
    }

    public static string EmitAlias(string concreteFullName, GenericGroup group, string typeArg)
    {
        var sb = new StringBuilder();
        sb.Append(Header);
        sb.Append($"// Monomorphization of {group.FullName}<T> (T = {typeArg}); see that type for members.\n");
        var package = Naming.PackageOf(concreteFullName);
        var shortName = Naming.ShortName(concreteFullName);
        EmitPackage(sb, package);
        sb.Append($"typedef {shortName} = {group.FullName}<{typeArg}>;\n");
        return sb.ToString();
    }

    private static void EmitPackage(StringBuilder sb, string package)
    {
        sb.Append(package.Length == 0 ? "package;\n\n" : $"package {package};\n\n");
    }

    private static void EmitImports(StringBuilder sb, bool needsResolvedMember)
    {
        // HlxRuntime is root-package (no import needed); ResolvedMember lives under hlx.runtime.
        if (needsResolvedMember) sb.Append("import hlx.runtime.ResolvedMember;\n\n");
    }

    private static void EmitNotes(StringBuilder sb, List<string> notes)
    {
        if (notes.Count == 0) return;
        sb.Append("// Members skipped by the generator for this class:\n");
        foreach (var n in notes) sb.Append("//   - ").Append(n.Replace("\n", " ")).Append('\n');
        sb.Append('\n');
    }

    // When a real get_/set_ proto exists (see GameField in Model.cs), route through it
    // via resolveMember/callResolved to preserve its side effects; otherwise fall back
    // to plain field reflection.
    private static void EmitFields(StringBuilder sb, string ownerFullName, List<GameField> fields, string indent)
    {
        foreach (var f in fields)
        {
            var fallback = f.Type.FallbackReason is { } r ? $" // {r}" : "";
            sb.Append($"{indent}public var {f.Name}(get, set):{f.Type.HaxeType};{fallback}\n");

            if (f.HasRealGetter)
            {
                var cacheVar = "__hlxMember_get_" + f.Name;
                sb.Append($"{indent}static var {cacheVar}:ResolvedMember;\n");
                sb.Append($"{indent}function get_{f.Name}():{f.Type.HaxeType} {{\n");
                sb.Append($"{indent}    if ({cacheVar} == null)\n");
                sb.Append($"{indent}        {cacheVar} = HlxRuntime.resolveMember(HlxRuntime.resolveType(\"{ownerFullName}\"), \"get_{f.Name}\");\n");
                sb.Append($"{indent}    return HlxRuntime.callResolved({cacheVar}, [this]);\n");
                sb.Append($"{indent}}}\n");
            }
            else
            {
                sb.Append($"{indent}inline function get_{f.Name}():{f.Type.HaxeType}\n");
                sb.Append($"{indent}    return HlxRuntime.resolveField(this, \"{f.Name}\");\n");
            }

            if (f.HasRealSetter)
            {
                var cacheVar = "__hlxMember_set_" + f.Name;
                sb.Append($"{indent}static var {cacheVar}:ResolvedMember;\n");
                sb.Append($"{indent}function set_{f.Name}(v:{f.Type.HaxeType}):{f.Type.HaxeType} {{\n");
                sb.Append($"{indent}    if ({cacheVar} == null)\n");
                sb.Append($"{indent}        {cacheVar} = HlxRuntime.resolveMember(HlxRuntime.resolveType(\"{ownerFullName}\"), \"set_{f.Name}\");\n");
                sb.Append($"{indent}    return HlxRuntime.callResolved({cacheVar}, [this, v]);\n");
                sb.Append($"{indent}}}\n");
            }
            else
            {
                sb.Append($"{indent}inline function set_{f.Name}(v:{f.Type.HaxeType}):{f.Type.HaxeType} {{\n");
                sb.Append($"{indent}    HlxRuntime.setField(this, \"{f.Name}\", v);\n");
                sb.Append($"{indent}    return v;\n");
                sb.Append($"{indent}}}\n");
            }
            sb.Append('\n');
        }
    }

    // Static-side twin of EmitFields: no real accessor -> resolveStaticField/
    // setStaticField; real get_/set_ proto -> resolveStaticMember/callResolved.
    private static void EmitStaticFields(StringBuilder sb, string ownerFullName, List<GameStaticField> fields, string indent)
    {
        foreach (var f in fields)
        {
            var fallback = f.Type.FallbackReason is { } r ? $" // {r}" : "";
            sb.Append($"{indent}public static var {f.Name}(get, set):{f.Type.HaxeType};{fallback}\n");

            if (f.HasRealGetter)
            {
                var cacheVar = "__hlxStatic_get_" + f.Name;
                sb.Append($"{indent}static var {cacheVar}:ResolvedMember;\n");
                sb.Append($"{indent}static function get_{f.Name}():{f.Type.HaxeType} {{\n");
                sb.Append($"{indent}    if ({cacheVar} == null)\n");
                sb.Append($"{indent}        {cacheVar} = HlxRuntime.resolveStaticMember(HlxRuntime.resolveType(\"{ownerFullName}\"), \"get_{f.Name}\");\n");
                sb.Append($"{indent}    return HlxRuntime.callResolved({cacheVar}, []);\n");
                sb.Append($"{indent}}}\n");
            }
            else
            {
                sb.Append($"{indent}static inline function get_{f.Name}():{f.Type.HaxeType}\n");
                sb.Append($"{indent}    return HlxRuntime.resolveStaticField(HlxRuntime.resolveType(\"{ownerFullName}\"), \"{f.Name}\");\n");
            }

            if (f.HasRealSetter)
            {
                var cacheVar = "__hlxStatic_set_" + f.Name;
                sb.Append($"{indent}static var {cacheVar}:ResolvedMember;\n");
                sb.Append($"{indent}static function set_{f.Name}(v:{f.Type.HaxeType}):{f.Type.HaxeType} {{\n");
                sb.Append($"{indent}    if ({cacheVar} == null)\n");
                sb.Append($"{indent}        {cacheVar} = HlxRuntime.resolveStaticMember(HlxRuntime.resolveType(\"{ownerFullName}\"), \"set_{f.Name}\");\n");
                sb.Append($"{indent}    return HlxRuntime.callResolved({cacheVar}, [v]);\n");
                sb.Append($"{indent}}}\n");
            }
            else
            {
                sb.Append($"{indent}static inline function set_{f.Name}(v:{f.Type.HaxeType}):{f.Type.HaxeType} {{\n");
                sb.Append($"{indent}    HlxRuntime.setStaticField(HlxRuntime.resolveType(\"{ownerFullName}\"), \"{f.Name}\", v);\n");
                sb.Append($"{indent}    return v;\n");
                sb.Append($"{indent}}}\n");
            }
            sb.Append('\n');
        }
    }

    private static void EmitMethods(StringBuilder sb, string ownerFullName, List<GameMethod> methods, string indent)
    {
        foreach (var m in methods)
        {
            var paramList = string.Join(", ", m.Params.Select((p, i) => $"a{i}:{p.HaxeType}"));
            var argsForCall = string.Join(", ", Enumerable.Range(0, m.Params.Count).Select(i => $"a{i}"));
            if (!m.IsStatic) argsForCall = argsForCall.Length == 0 ? "this" : $"this, {argsForCall}";

            var notes = m.Params.Select((p, i) => (Label: $"arg{i}", p.FallbackReason))
                .Append((Label: "return", m.Return.FallbackReason))
                .Where(x => x.FallbackReason != null)
                .Select(x => $"{x.Label}: {x.FallbackReason}")
                .ToList();
            if (notes.Count > 0)
                sb.Append($"{indent}// {string.Join("; ", notes)}\n");

            var cacheVar = (m.IsStatic ? "__hlxStatic_" : "__hlxMember_") + m.Name;
            var resolveCall = m.IsStatic ? "resolveStaticMember" : "resolveMember";
            var isVoid = m.Return.HaxeType == "Void";

            sb.Append($"{indent}static var {cacheVar}:ResolvedMember;\n");
            sb.Append($"{indent}public {(m.IsStatic ? "static " : "")}function {m.Name}({paramList}):{m.Return.HaxeType} {{\n");
            sb.Append($"{indent}    if ({cacheVar} == null)\n");
            sb.Append($"{indent}        {cacheVar} = HlxRuntime.{resolveCall}(HlxRuntime.resolveType(\"{ownerFullName}\"), \"{m.Name}\");\n");
            sb.Append(isVoid
                ? $"{indent}    HlxRuntime.callResolved({cacheVar}, [{argsForCall}]);\n"
                : $"{indent}    return HlxRuntime.callResolved({cacheVar}, [{argsForCall}]);\n");
            sb.Append($"{indent}}}\n\n");
        }
    }
}
